language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements/yogit.txt -r requirements/tests.txt -r requirements/codesanity.txt
script:
- pytest -vv -s yogit/tests
- ci/blackify --check
deploy:
  provider: pypi
  user: hasboeuf
  password:
    secure: Fz9H3WuBQPnn0X5gFYMLpDXfPXgLFR0VH51Og/JFWKdqHkY8nZf6S2bGvSgLF4YDNSMk05fXu2Hk/Hf6FYa0LKs9ysqrKvpOYDfT79lBhrUmr+Fn63gM1Ob6QmbxQb4SjzvP3HuJkZ4GQ5ago5G+9l+v9p2AanieS3LuUQnX7uil1yJW1ylcpKAJY4FQ1xraEkyugPPjJbSxHhX0VUTBW1gn5NnXrYs7e4+isv75KrYdyS0TgQ7b/8TVUzXX4renYjWwvSuULKge3+WnxZF3+UpBD/Gn5PJMEHT4ABpMzHpYImt/cypXfGzI9zV70FQkhGdkjAo8cFRU8L7ovdcGBOvABq8F9x4h0PF0EytalKOVxv1jUoEIWVpWeMR/4WQMb3awN5TEfdDqOiof+C1AygNSG9rVVONRnAGUQCRLHoMn4V56JsfBK+pFM1pvxbezO4cnpbo41L8nCdndHlku7tEsdi9UeOiWDRKvgJAG3V9l2KSkt3njAJy/jQyd88umR77hZkYwjSlzhDoTU8QnenWnicNJaX5NbyCrdNH+OrXEv8jNA48jW2lhCyx/9MVPb7AI7YQesvlFZuj7vbSqmBaGFmU83bQ405PQN50Si01PBs7wciB1djBLxkqh0WoAb4513s/aRLQKQfknGPxsnZWd+Yhi1NmucfktDyR5S3Q=
  on:
    branch: master
  skip_existing: true
